import os
import re
from typing import Annotated, TypedDict
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages, convert_to_messages
from langchain_huggingface import HuggingFaceEndpoint, ChatHuggingFace
from langchain_core.messages import HumanMessage, AIMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.utils.function_calling import convert_to_openai_tool
from pydantic import BaseModel, Field


# 1. Initialize the Hugging Face GLM Chat Model

repo_id = "zai-org/GLM-5.3"
llm = HuggingFaceEndpoint(
    repo_id=repo_id,
    task="text-generation",
    max_new_tokens=2048,
    temperature=0.7,
    huggingfacehub_api_token=os.getenv("HF_TOKEN")
)


# Wrap it in ChatHuggingFace to properly manage structured chat templates
chat_model = ChatHuggingFace(llm=llm)

    
raw_messages = {"messages": [
        {"role": "system","content": ("""You are a high-level programming expert designer. User will request to code a program in less than 251 words. You need to perform the below.
        Your response must follow these steps:
        1. Whenever possible, use your step by step reasoning capability to break down the problem in to simple steps. 
        2. Number of steps should be less than 9.
        3. Very simple program like adding two number, calculating factorial, etc. should be solved in 1 step. This is because one function
           will be assigned to a step in a later state by a differnt model. Only a process that needs a seperate function or class 
           should be assigned a specific steps.
        4. the 10th step or the last step is always a process to orchestrae the steps into a working code.
        5. Eachstep should be a single line of text.
        6. Very simple logic that can be coded in a single function or class should be solved in a single step. Complex logic that needs multiple functions or classes should be broken down into multiple steps.
        7. No additional text should be added to the steps.
        8. each step should be explained in a few words at the best possibe.
        9. The code will be generated by a different model and it will be always a Pythpn code
        """)}
]}


# Instructions handed to the model for every coding step. They are sent as part of
# the shared message history, so the model always sees the code already produced
# for the earlier steps and stays consistent with it.
CODER_INSTRUCTIONS = """You are a Python developer implementing one step of an agreed plan.
Rules:
1. Implement ONLY the step given below, nothing more.
2. Reuse the names, signatures and conventions of the code already produced in this conversation.
3. Do not repeat code written in an earlier step; import or call it instead.
4. Return Python code only, no explanation and no markdown fences.
"""


# 2. Define the Graph State
class AgentState(TypedDict):
    # add_messages appends new messages to the existing list rather than overwriting it,
    # which is what keeps one shared context across every node of the graph
    messages: Annotated[list, add_messages]
    response: object
    steps: list[str]
    current_step: int
    files: list[str]
    output_dir: str

class deepseek_response(BaseModel):
    steps: list[str] = Field(description="List of steps for the coding logic")

tool_schema = convert_to_openai_tool(deepseek_response)

struct_deep_model = chat_model.with_structured_output(tool_schema)


def extract_steps(response):
    """Normalises the structured output into a plain list of step descriptions."""
    if isinstance(response, dict):
        return list(response.get("steps", []))
    return list(getattr(response, "steps", []))


def strip_code_fences(text: str) -> str:
    """Removes a surrounding ```python ... ``` block if the model added one."""
    fenced = re.match(r"\s*```(?:python)?\s*\n(.*?)\n?\s*```\s*$", text, re.DOTALL)
    return fenced.group(1) if fenced else text.strip()


# 3. Define the Nodes (The processing steps)
def call_deepseek_agent(state: AgentState):
    """Sends the current message history to GLM and stores the planned steps."""
    messages = state["messages"]
    response = struct_deep_model.invoke(messages)
    steps = extract_steps(response)
    return {"response": response, "steps": steps, "current_step": 0, "files": []}


def call_coding_agent(state: AgentState):
    """Generates the code for one step at a time and writes it to 'Step-#.txt'.

    Both the request and the generated code are appended to the shared message
    history, so the next run of this node sees everything written so far.
    """
    steps = state["steps"]
    index = state["current_step"]
    step = steps[index]
    step_number = index + 1

    request = HumanMessage(content=(
        f"{CODER_INSTRUCTIONS}\n"
        f"Step {step_number} of {len(steps)}: {step}"
    ))

    print(f"Generating code for step {step_number}/{len(steps)}: {step}")
    answer = chat_model.invoke(state["messages"] + [request])
    code = strip_code_fences(answer.content)

    output_dir = state.get("output_dir") or os.getcwd()
    file_path = os.path.join(output_dir, f"Step-{step_number}.txt")
    with open(file_path, "w", encoding="utf-8") as handle:
        handle.write(code)
    print(f"  -> written to {file_path}")

    return {
        "messages": [request, AIMessage(content=code)],
        "current_step": step_number,
        "files": state["files"] + [file_path],
    }


# 4. Conditional edge: keep looping on the coding node until every step is done
def steps_remaining(state: AgentState):
    """Returns 'coder' while steps are pending, otherwise ends the loop."""
    if state["current_step"] < len(state["steps"]):
        return "coder"
    return END


# 5. Build the LangGraph Workflow
workflow = StateGraph(AgentState)

# Add the planning node and the code generation node
workflow.add_node("agent", call_deepseek_agent)
workflow.add_node("coder", call_coding_agent)

# Set up flow control: entry point -> planning node -> coding loop -> exit point
workflow.add_edge(START, "agent")
workflow.add_edge("agent", "coder")
workflow.add_conditional_edges("coder", steps_remaining, {"coder": "coder", END: END})

# Compile into an executable application
app = workflow.compile()


# 6. Callable entry points (used by the CLI below and by the Flask API)

# The planner prompt caps the request at 250 words
MAX_REQUEST_WORDS = 250


def generate_steps_and_code(description: str, output_dir: str | None = None) -> dict:
    """Runs the full graph for one coding request.

    Returns a dict with:
        status  -- "success" or "failure"
        message -- human readable outcome
        steps   -- list of planned steps (empty on failure)
        files   -- list of 'Step-#.txt' paths written (empty on failure)
    """
    output_dir = output_dir or os.getcwd()

    if not description or not description.strip():
        return {
            "status": "failure",
            "message": "A coding description is required.",
            "steps": [],
            "files": [],
        }

    word_count = len(description.split())
    if word_count > MAX_REQUEST_WORDS:
        return {
            "status": "failure",
            "message": (
                f"The coding description has {word_count} words; "
                f"the limit is {MAX_REQUEST_WORDS}."
            ),
            "steps": [],
            "files": [],
        }

    os.makedirs(output_dir, exist_ok=True)

    initial_state = {
        "messages": convert_to_messages([
            raw_messages["messages"][0],
            {"role": "user", "content": description}
        ]),
        "steps": [],
        "current_step": 0,
        "files": [],
        "output_dir": output_dir,
    }

    try:
        # The coding node loops once per step, so lift the default recursion limit
        final_state = app.invoke(initial_state, config={"recursion_limit": 100})
    except Exception as exc:  # model, network or graph failure
        return {
            "status": "failure",
            "message": f"Code generation failed: {exc}",
            "steps": [],
            "files": [],
        }

    steps = final_state.get("steps", [])
    if not steps:
        return {
            "status": "failure",
            "message": "The model did not return any step for this description.",
            "steps": [],
            "files": [],
        }

    return {
        "status": "success",
        "message": f"Generated code for {len(steps)} step(s).",
        "steps": steps,
        "files": final_state.get("files", []),
    }


def read_step_code(step_number: int, output_dir: str | None = None) -> dict:
    """Reads back the code written for a single step.

    Returns a dict with status, message and (on success) the code text.
    """
    output_dir = output_dir or os.getcwd()

    if step_number < 1:
        return {
            "status": "failure",
            "message": "Step number must be 1 or greater.",
            "code": None,
        }

    file_path = os.path.join(output_dir, f"Step-{step_number}.txt")
    if not os.path.isfile(file_path):
        return {
            "status": "failure",
            "message": f"No generated code found for step {step_number}.",
            "code": None,
        }

    with open(file_path, "r", encoding="utf-8") as handle:
        code = handle.read()

    return {
        "status": "success",
        "message": f"Code for step {step_number}.",
        "code": code,
        "file": file_path,
    }


# 7. Command line execution
if __name__ == "__main__":
    usrrequest = input("Enter your programming request (less than 250 words): ")

    print("Sending request to GLM via Hugging Face...")
    result = generate_steps_and_code(usrrequest)

    print()
    print("[" + result["status"].upper() + "] " + result["message"])

    if result["status"] == "success":
        print()
        print("[Planned steps]:")
        for step in result["steps"]:
            print(step)

        print()
        print("[Generated files]:")
        for file_path in result["files"]:
            print(file_path)
