import gradio as gr
from transformers import BlipProcessor, BlipForConditionalGeneration

print("1. Text Generation with Gradio")
print("2. Image Captioning with Gradio/BLIP")
print("3. Exit")
option=input("Enter an option (1, 2, or 3) and press Enter to continue...")

if option == '1':
    print("You selected Text Generation with Gradio")
    def greet(name, intensity):
        return "Hello, " + name + "!" * int(intensity)
        demo = gr.Interface(
        fn=greet,
        inputs=["text", "slider"],
        outputs=["text"],
        )
        demo.launch(server_name="127.0.0.1", server_port= 7860)

elif option == '2':
    print("You selected Image Captioning with Gradio/BLIP")
    processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
    model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base")

    def generate_caption(image):
        inputs = processor(images=image, return_tensors="pt")
        out = model.generate(**inputs)
        caption = processor.decode(out[0], skip_special_tokens=True)
        return caption

    demo = gr.Interface(
        fn=generate_caption,
        inputs=gr.Image(type="pil"),
        outputs="text",
        title="Image Captioning with BLIP",
        description="Upload an image and get a caption generated by the BLIP model."
    )

    demo.launch(server_name="127.0.0.1", server_port=7860)

elif option == '3':
    print("Exiting the program.")
    exit()
    
